### ISSUE TITLE
Use illumina short reads of parents

### ISSUE THREAD

**Issue by qhli1** [human-pangenomics/hpgp-data#6]
Hi, the illumina short reads of parents are in the different folders. And each folder contains sevral files from the different lanes. Do I need to merge the files from different lanes and different folder together before using them? Thank you.

**Comment by skoren** [comment]
I'm not sure what your intended use case is but if you want the full coverage for each parent then yes, you'd need to download the files from all folders/lanes and analyze them together. You shouldn't actually have to merge them into a single file since most programs can handle multiple input files.

**Comment by qhli1** [comment]
Got it. Thanks for your reply!
